/**
 * THE CONTENT GUARD.
 *
 * Reads content/claims.json and reports what is still unverified.
 *
 *   node scripts/check-content.mjs                # report, exit 0
 *   node scripts/check-content.mjs --production   # FAIL if a launch blocker is unresolved
 *   node scripts/check-content.mjs --write-checklist
 *
 * The point is that the honesty principle stops depending on somebody
 * remembering it. A production content build cannot succeed while the site
 * would state an unverified fact.
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const args = new Set(process.argv.slice(2));
const PRODUCTION = args.has("--production");
const WRITE = args.has("--write-checklist");

const raw = JSON.parse(await readFile(path.resolve("content/claims.json"), "utf8"));
const claims = raw.claims;

const resolved = (c) => Boolean(c.verified && c.asOf);
const launchBlockers = claims.filter((c) => c.blocksLaunch && !resolved(c));
const implBlockers = claims.filter((c) => c.blocksImplementation && !resolved(c));
const safe = claims.filter((c) => !c.blocksLaunch && !resolved(c));

console.log(`content claims: ${claims.length}`);
console.log(`  resolved                    ${claims.filter(resolved).length}`);
console.log(`  unresolved, blocks launch   ${launchBlockers.length}`);
console.log(`  unresolved, blocks build    ${implBlockers.length}`);
console.log(`  unresolved, safe to ship    ${safe.length}   (fallback already applied)`);

if (launchBlockers.length) {
  console.log("\nUNRESOLVED LAUNCH BLOCKERS");
  for (const c of launchBlockers) {
    console.log(`  · ${c.id.padEnd(30)} ${c.label}`);
    console.log(`    ${c.location}`);
  }
}

if (WRITE) {
  const out = path.resolve("docs/redesign-2026/CONTENT-REQUIRED.md");
  await mkdir(path.dirname(out), { recursive: true });

  const fmt = (v) =>
    v === null || v === undefined
      ? "_none — nothing is shown_"
      : Array.isArray(v)
        ? v.length === 0
          ? "_empty — the section is built to work without them_"
          : v.join(" · ")
        : String(v);

  const block = (c) => `
### ${c.label}

| | |
|---|---|
| **Claim id** | \`${c.id}\` |
| **Appears in** | ${c.location} |
| **Why it is needed** | ${c.why} |
| **Current dev value** | ${fmt(c.value)}${c.unit ? ` ${c.unit}` : ""} ${resolved(c) ? "" : "— **DEVELOPMENT PLACEHOLDER**"} |
| **Measurement date** | ${c.asOf ?? "**required — not supplied**"} |
| **Source / verification** | ${c.source ?? "**required — not supplied**"} |
| **Blocks implementation** | ${c.blocksImplementation ? "**Yes**" : "No"} |
| **Blocks public launch** | ${c.blocksLaunch ? "**Yes**" : "No"} |
| **Fallback if never supplied** | ${c.fallback} |
`;

  const md = `# R.Pay — content and permissions required

**Generated from \`content/claims.json\` by \`scripts/check-content.mjs --write-checklist\`.**
Do not edit this file by hand; edit the registry and regenerate, so the checklist and the
site can never drift apart.

_Last generated against ${claims.length} declared claims._

---

## How to read this

Every public factual statement on the site is declared in one registry. A claim is
**publishable** only when it is both \`verified\` and carries an \`asOf\` measurement date —
verified-without-a-date counts as unverified on purpose, because the date is half of what
makes a number honest.

Until then the interface renders the **fallback**, not a blank. Nothing here stops the site
being built; several items stop it being published.

- **${claims.filter(resolved).length}** resolved
- **${launchBlockers.length}** unresolved and blocking launch
- **${implBlockers.length}** unresolved and blocking implementation
- **${safe.length}** unresolved but safe to ship as-is

Run \`node scripts/check-content.mjs --production\` to fail a build while any launch blocker
is outstanding.

---

## Blocks public launch

These must be resolved before the site goes live.

${launchBlockers.map(block).join("\n---\n")}

---

## Unresolved, but safe to ship

The fallback is already the shipped behaviour. Resolving these improves the page; not
resolving them costs nothing.

${safe.length ? safe.map(block).join("\n---\n") : "_None._"}

---

## Resolved

${claims.filter(resolved).length
  ? claims.filter(resolved).map((c) => `- **${c.label}** — \`${c.id}\`, as of ${c.asOf}, source: ${c.source}`).join("\n")
  : "_None yet._"}

---

## What is deliberately NOT on this list

Anything the site does not claim. The page states no hardware certification, no uptime
percentage, no regulator relationship, no customer count and no superlative, so none of
those appear here. The shortest way to keep a claim honest is not to make it.
`;

  await writeFile(out, md, "utf8");
  console.log(`\nwrote ${out}`);
}

if (PRODUCTION && launchBlockers.length) {
  console.error(
    `\nREFUSING A PRODUCTION CONTENT BUILD: ${launchBlockers.length} launch-blocking claim(s) are unverified.\n` +
    `Resolve them in content/claims.json (set verified:true with an asOf date and a source),\n` +
    `or accept the documented fallback by setting blocksLaunch:false with a note.`,
  );
  process.exit(1);
}

if (implBlockers.length) {
  console.error(`\n${implBlockers.length} claim(s) block implementation.`);
  process.exit(1);
}
