export const LOGOS: { alt: string; uri: string }[] = [
  { alt: 'Al Nadej', uri: "/assets/logos/al-nadej.webp" },
  { alt: 'Boulevard World', uri: "/assets/logos/boulevard-world.webp" },
  { alt: 'Roshn', uri: "/assets/logos/roshn.svg" },
  { alt: 'Al Deera', uri: "/assets/logos/al-deera.webp" },
  { alt: 'Al Khozama', uri: "/assets/logos/al-khozama.webp" },
  { alt: 'LuLu', uri: "/assets/logos/lulu.webp" },
  { alt: 'Sela', uri: "/assets/logos/sela.webp" },
  { alt: 'Boulevard City', uri: "/assets/logos/boulevard-city.webp" },
  { alt: 'Malahi', uri: "/assets/logos/malahi.webp" },
  { alt: 'Dar Al Arkan', uri: "/assets/logos/dar-al-arkan.webp" },
  { alt: 'Hamat', uri: "/assets/logos/hamat.webp" },
  { alt: 'Kinan', uri: "/assets/logos/kinan.webp" },
  { alt: 'Shawarma House', uri: "/assets/logos/shawarma-house.webp" },
];
